CREATE DATABASE TEMVAGA;
USE TEMVAGA;

CREATE TABLE PASSAGEM (
PROMOÇÃO DECIMAL(5,2),
CODIGO_PASSAGEM INTEGER PRIMARY KEY auto_increment,
VALOR_VIAGEM decimal(9,6),
CODIGO_DESTINO INTEGER,
CPF VARCHAR(50)
);

CREATE TABLE CLIENTE (
NOME VARCHAR(60),
IDADE VARCHAR(6),
CPF VARCHAR(20) PRIMARY KEY,
TELEFONE VARCHAR(10),
EMAIL VARCHAR(50),
DATA_NASCIMENTO datetime(6),
ENDEREÇO VARCHAR(50),
CEP VARCHAR(20),
BAIRRO VARCHAR(50),
NUMERO VARCHAR(10),
PAIS VARCHAR(50),
ESTADO VARCHAR(50)
);
CREATE TABLE DESTINO (
CODIGO_DESTINO INTEGER PRIMARY KEY auto_increment,
ESTADO VARCHAR(100),
CIDADE VARCHAR(100)
);

ALTER TABLE PASSAGEM ADD FOREIGN KEY(CODIGO_DESTINO) REFERENCES DESTINO (CODIGO_DESTINO);
ALTER TABLE PASSAGEM ADD FOREIGN KEY(CPF) REFERENCES CLIENTE (CPF);

SELECT*FROM CLIENTE;
SELECT*FROM DESTINO;
SELECT*FROM PASSAGEM;

